# -*- coding: utf-8 -*-
"""system V11 .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fTnHF14zY79OLC4x59eotS9J1N5tADSJ
"""

import subprocess
import os
import time

print("📦 修复 NumPy...")
subprocess.run(['pip', 'install', 'numpy==1.26.4', '-q'], capture_output=True)

from google.colab import drive
drive.mount('/content/drive')

print("📦 安装依赖...")
subprocess.run(['pip', 'install', 'f5-tts', 'flask', 'flask-cors', 'pyngrok',
                'soundfile', 'librosa', 'moviepy', 'pillow', 'gtts', 'ollama',
                'diffusers', 'transformers', 'accelerate', 'safetensors', '-q'], capture_output=True)

print("📦 安装 Ollama...")
subprocess.run(['curl', '-fsSL', 'https://ollama.com/install.sh', '-o', '/tmp/install.sh'], capture_output=True)
subprocess.run(['sh', '/tmp/install.sh'], capture_output=True, text=True)

subprocess.Popen(['ollama', 'serve'], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
time.sleep(5)

print("📥 下载 Gemma 3 4B...")
subprocess.run(['ollama', 'pull', 'gemma3:4b'])

print("🔧 设置 ngrok...")
subprocess.run(['ngrok', 'config', 'add-authtoken', '35yagLESS5O0a1grPmIHdEJnp5S_4pi3TBc9b5bSpd5kp8SEM'], capture_output=True)

print("✅ Cell 1 完成！请重启 Runtime 后执行 Cell 2")

# ==========================================
# Cell 2: 骨感字典后端 v11-fixed2
# 修正：Ollama timeout、段落生成邏輯
# ==========================================

import os
import sys
import re
import json
import base64
import io
import torch
import numpy as np
import soundfile as sf
from PIL import Image, ImageDraw, ImageFont
from flask import Flask, request, jsonify, Response, stream_with_context
from flask_cors import CORS
import ollama
from gtts import gTTS
import traceback
import gc
import librosa
import subprocess
import time
import threading

from f5_tts.api import F5TTS

app = Flask(__name__)
CORS(app)

OLLAMA_MODEL = "gemma3:4b"
VISION_MODEL = "gemma3:4b"

f5_model = None
sdxl_pipe = None
svd_pipe = None

F5_NFE_STEP = 64
F5_CFG_STRENGTH = 2.0
F5_SPEED = 0.9

SVD_MOTION = 80
SVD_FRAMES = 25
SVD_FPS = 6

VOICE_REFERENCES = {
    "villager_zh": {"path": "/content/drive/MyDrive/Voice data/Minecraft Villager chinese.wav", "text": "哇！你看这个甲骨文字！它就像一个小图画一样，太神奇了！这就是三千年前祖先的智慧啊！"},
    "trump_zh": {"path": "/content/drive/MyDrive/Voice data/Donald Trump chinese.wav", "text": "哇！你看这个甲骨文字！它就像一个小图画一样，太神奇了！这就是三千年前祖先的智慧啊！"},
    "obama_zh": {"path": "/content/drive/MyDrive/Voice data/Barack Obama chinese.wav", "text": "哇！你看这个甲骨文字！它就像一个小图画一样，太神奇了！这就是三千年前祖先的智慧啊！"},
    "biden_zh": {"path": "/content/drive/MyDrive/Voice data/Joe Biden chinese.wav", "text": "哇！你看这个甲骨文字！它就像一个小图画一样，太神奇了！这就是三千年前祖先的智慧啊！"},
    "taylor_zh": {"path": "/content/drive/MyDrive/Voice data/Taylor Swift chinese.wav", "text": "哇！你看这个甲骨文字！它就像一个小图画一样，太神奇了！这就是三千年前祖先的智慧啊！"},
    "morgan_zh": {"path": "/content/drive/MyDrive/Voice data/Morgan Freeman chinese.wav", "text": "哇！你看这个甲骨文字！它就像一个小图画一样，太神奇了！这就是三千年前祖先的智慧啊！"},
    "hillary_zh": {"path": "/content/drive/MyDrive/Voice data/Hillary Clinton chinese.wav", "text": "哇！你看这个甲骨文字！它就像一个小图画一样，太神奇了！这就是三千年前祖先的智慧啊！"},
    "villager_en": {"path": "/content/drive/MyDrive/Voice data/Minecraft Villager english.wav", "text": "Wow! Look at this oracle bone character! It's like a tiny picture! So amazing! This is the wisdom of our ancestors from three thousand years ago!"},
    "trump_en": {"path": "/content/drive/MyDrive/Voice data/Donald Trump english.wav", "text": "Wow! Look at this oracle bone character! It's like a tiny picture! So amazing! This is the wisdom of our ancestors from three thousand years ago!"},
    "obama_en": {"path": "/content/drive/MyDrive/Voice data/Barack Obama english.wav", "text": "Wow! Look at this oracle bone character! It's like a tiny picture! So amazing! This is the wisdom of our ancestors from three thousand years ago!"},
    "biden_en": {"path": "/content/drive/MyDrive/Voice data/Joe Biden english.wav", "text": "Wow! Look at this oracle bone character! It's like a tiny picture! So amazing! This is the wisdom of our ancestors from three thousand years ago!"},
    "taylor_en": {"path": "/content/drive/MyDrive/Voice data/Taylor Swift english.wav", "text": "Wow! Look at this oracle bone character! It's like a tiny picture! So amazing! This is the wisdom of our ancestors from three thousand years ago!"},
    "morgan_en": {"path": "/content/drive/MyDrive/Voice data/Morgan Freeman english.wav", "text": "Wow! Look at this oracle bone character! It's like a tiny picture! So amazing! This is the wisdom of our ancestors from three thousand years ago!"},
    "hillary_en": {"path": "/content/drive/MyDrive/Voice data/Hillary Clinton english.wav", "text": "Wow! Look at this oracle bone character! It's like a tiny picture! So amazing! This is the wisdom of our ancestors from three thousand years ago!"},
}

CHARACTER_TRAITS_ZH = {
    "trump": "川普：自大夸张，爱说'最棒的'、'没有人比我更懂'",
    "obama": "欧巴马：理性优雅，爱说'让我告诉你'",
    "biden": "拜登：亲切老爷爷，爱说'来吧伙计'",
    "taylor": "泰勒：感性诗意，用音乐比喻",
    "morgan": "摩根：睿智深沉，纪录片旁白感",
    "hillary": "希拉蕊：专业犀利",
    "villager": "村民：淳朴天真"
}

CHARACTER_TRAITS_EN = {
    "trump": "Trump: arrogant, loves 'the best', 'nobody knows more than me'",
    "obama": "Obama: rational, elegant, 'let me tell you'",
    "biden": "Biden: friendly grandpa, 'come on man'",
    "taylor": "Taylor: emotional, poetic, music metaphors",
    "morgan": "Morgan: wise, deep, documentary narrator",
    "hillary": "Hillary: professional, sharp",
    "villager": "Villager: simple, innocent"
}

CHARACTER_IMAGE_PROMPTS = {
    "trump": "Donald Trump in blue suit with red tie",
    "obama": "Barack Obama in elegant dark suit",
    "biden": "Joe Biden in suit smiling warmly",
    "taylor": "Taylor Swift in glamorous dress",
    "morgan": "Morgan Freeman in wise appearance",
    "hillary": "Hillary Clinton in professional attire",
    "villager": "Chinese village elder in traditional clothes"
}

STORYBOOK_SCENES = [
    "ancient Chinese museum with bronze artifacts, warm lighting",
    "traditional Chinese study room with scrolls and ink brushes, candlelight",
    "ancient Chinese craftsman carving characters, historical workshop",
    "modern classroom with Chinese calligraphy, educational setting",
    "traditional Chinese painting style, mountains and clouds background",
    "celebration of Chinese cultural heritage, red and gold decorations",
]

def is_chinese(lang):
    return 'zh' in lang.lower()

def get_lang_suffix(lang):
    return '_zh' if is_chinese(lang) else '_en'

def get_voice_id(voice_name, lang):
    base = voice_name.replace('_zh', '').replace('_en', '')
    return f"{base}{get_lang_suffix(lang)}"

def get_trait(voice_name, lang):
    base = voice_name.replace('_zh', '').replace('_en', '')
    if is_chinese(lang):
        return CHARACTER_TRAITS_ZH.get(base, "专业风格")
    return CHARACTER_TRAITS_EN.get(base, "professional style")

def get_char_image(voice_name):
    base = voice_name.replace('_zh', '').replace('_en', '')
    return CHARACTER_IMAGE_PROMPTS.get(base, "a presenter")

def clean_script(text):
    if not text:
        return ""
    preamble_patterns = [
        r'^[Oo]kay[,.]?\s*', r'^[Hh]ere\'?s?\s*(a\s+)?(joke|story|script)[^:：]*[:：]\s*',
        r'^[Ss]ure[,!.]?\s*', r'^[Aa]lright[,.]?\s*', r'^[Ll]et me[^:：]*[:：]\s*',
        r'^[Hh]ere (is|are)[^:：]*[:：]\s*', r'^好的[,，]?\s*', r'^以下是[^:：]*[:：]\s*',
    ]
    for p in preamble_patterns:
        text = re.sub(p, '', text, flags=re.IGNORECASE)
    text = re.sub(r'（[^）]*）', '', text)
    text = re.sub(r'\([^)]*\)', '', text)
    text = re.sub(r'【[^】]*】', '', text)
    text = re.sub(r'\[[^\]]*\]', '', text)
    text = re.sub(r'\*[^*]*\*', '', text)
    text = re.sub(r'「([^」]*)」', r'\1', text)
    patterns = [r'深吸', r'目光', r'微笑', r'笑着', r'点头', r'摇头', r'沉思',
                r'停顿', r'清嗓', r'叹气', r'眨眼', r'挥手', r'转身', r'看向',
                r'sighs', r'smiles', r'nods', r'pauses', r'looks']
    for p in patterns:
        text = re.sub(rf'{p}[^，。！？,.!?]*[，。,.!?]?', '', text, flags=re.IGNORECASE)
    text = re.sub(r'[，,]{2,}', '，', text)
    text = re.sub(r'^[，,。\s\n:：]+', '', text)
    text = text.strip()
    if text.startswith('"') and text.endswith('"'):
        text = text[1:-1]
    return text.strip()

# ===== Ollama (增加 timeout) =====

def restart_ollama():
    print("   [Ollama] Restarting...")
    subprocess.run(['pkill', '-9', '-f', 'ollama'], capture_output=True)
    time.sleep(3)
    subprocess.Popen(['ollama', 'serve'], stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    time.sleep(10)
    print("   [Ollama] Restarted")

def ensure_ollama():
    result = {"ok": False}
    def test():
        try:
            ollama.generate(model=OLLAMA_MODEL, prompt="hi", stream=False)
            result["ok"] = True
        except:
            pass
    t = threading.Thread(target=test)
    t.start()
    t.join(timeout=20)
    if not result["ok"]:
        restart_ollama()
        t = threading.Thread(target=test)
        t.start()
        t.join(timeout=20)
    print("[Ollama] OK" if result["ok"] else "[Ollama] Warning")

def call_ollama(func, **kwargs):
    """增加 timeout 到 120 秒"""
    for attempt in range(3):
        try:
            result = {"value": None, "error": None}
            def run():
                try:
                    result["value"] = func(**kwargs)
                except Exception as e:
                    result["error"] = e
            t = threading.Thread(target=run)
            t.start()
            t.join(timeout=120)  # 增加到 120 秒
            if result["value"]:
                return result["value"]
            if result["error"]:
                raise result["error"]
            raise Exception("Ollama timeout")
        except Exception as e:
            print(f"   Ollama attempt {attempt+1} failed: {e}")
            if attempt < 2:
                restart_ollama()
    raise Exception("Ollama failed after 3 attempts")

def extract_json(text):
    """從文本中提取 JSON，處理各種格式"""
    if not text:
        return None

    # 移除 markdown code block
    text = re.sub(r'```json\s*', '', text)
    text = re.sub(r'```\s*', '', text)
    text = text.strip()

    # 嘗試直接解析
    try:
        return json.loads(text)
    except:
        pass

    # 嘗試找到 JSON 對象
    m = re.search(r'\{[^{}]*\}', text, re.DOTALL)
    if m:
        try:
            return json.loads(m.group())
        except:
            pass

    # 嘗試找到更深層的 JSON
    m = re.search(r'\{.*\}', text, re.DOTALL)
    if m:
        try:
            return json.loads(m.group())
        except:
            pass

    return None

def parse_markdown_response(text):
    """從 Markdown 格式回應中提取資訊"""
    result = {"character": "?", "pinyin": "", "meaning": "", "confidence": 0.5}

    # 提取現代中文字
    patterns = [
        r'\*\*現代中文字[:\s]*\*\*\s*([^\s\*]+)',
        r'現代中文字[:\s]*([^\s,，]+)',
        r'character[:\s]*["\']?([^"\'，,\s]+)',
    ]
    for p in patterns:
        m = re.search(p, text, re.IGNORECASE)
        if m:
            char = m.group(1).strip()
            # 清理括號內容
            char = re.sub(r'[（\(].*?[）\)]', '', char).strip()
            if char and len(char) <= 4:
                result["character"] = char
                break

    # 提取拼音
    patterns = [
        r'\*\*拼音[:\s]*\*\*\s*([a-zA-Zāáǎàēéěèīíǐìōóǒòūúǔùǖǘǚǜ]+\d?)',
        r'拼音[:\s]*([a-zA-Zāáǎàēéěèīíǐìōóǒòūúǔùǖǘǚǜ]+\d?)',
        r'pinyin[:\s]*["\']?([a-zA-Zāáǎàēéěèīíǐìōóǒòūúǔùǖǘǚǜ]+\d?)',
    ]
    for p in patterns:
        m = re.search(p, text, re.IGNORECASE)
        if m:
            result["pinyin"] = m.group(1).strip()
            break

    # 提取含義
    patterns = [
        r'\*\*含義[:\s]*\*\*\s*([^*\n]+)',
        r'含義[:\s]*([^，。\n]{5,50})',
        r'meaning[:\s]*["\']?([^"\']+)',
    ]
    for p in patterns:
        m = re.search(p, text, re.IGNORECASE)
        if m:
            meaning = m.group(1).strip()
            if len(meaning) > 5:
                result["meaning"] = meaning[:100]
                break

    # 提取信心度
    m = re.search(r'(?:confidence|信心度)[:\s]*["\']?(0\.\d+|\d+%?)', text, re.IGNORECASE)
    if m:
        conf = m.group(1)
        if '%' in conf:
            result["confidence"] = float(conf.replace('%', '')) / 100
        else:
            result["confidence"] = float(conf)

    return result

# ===== F5-TTS =====

def load_f5():
    global f5_model
    if f5_model is None:
        unload_sdxl()
        unload_svd()
        gc.collect()
        torch.cuda.empty_cache()
        print("   Loading F5-TTS...")
        f5_model = F5TTS()
        print("   F5-TTS loaded")

def unload_f5():
    global f5_model
    if f5_model is not None:
        del f5_model
        f5_model = None
        gc.collect()
        torch.cuda.empty_cache()

def gen_audio(text, voice_id, lang, output_path):
    ref = VOICE_REFERENCES.get(voice_id)
    if not ref or not os.path.exists(ref['path']):
        print(f"   Voice {voice_id} not found, using gTTS")
        tts = gTTS(text=text, lang='zh-TW' if is_chinese(lang) else 'en')
        tts.save(output_path)
        return output_path
    wav, sr, _ = f5_model.infer(
        ref_file=ref['path'], ref_text=ref['text'], gen_text=text,
        nfe_step=F5_NFE_STEP, cfg_strength=F5_CFG_STRENGTH, speed=F5_SPEED
    )
    sf.write(output_path, wav, sr)
    print(f"   Audio saved: {output_path}")
    return output_path

# ===== SDXL =====

def load_sdxl():
    global sdxl_pipe
    if sdxl_pipe is None:
        unload_f5()
        unload_svd()
        gc.collect()
        torch.cuda.empty_cache()
        print("   Loading SDXL...")
        from diffusers import StableDiffusionXLPipeline
        sdxl_pipe = StableDiffusionXLPipeline.from_pretrained(
            "stabilityai/stable-diffusion-xl-base-1.0",
            torch_dtype=torch.float16, variant="fp16", use_safetensors=True
        ).to("cuda")
        sdxl_pipe.enable_model_cpu_offload()
        print("   SDXL loaded")

def unload_sdxl():
    global sdxl_pipe
    if sdxl_pipe is not None:
        del sdxl_pipe
        sdxl_pipe = None
        gc.collect()
        torch.cuda.empty_cache()

def gen_image(prompt, output_path, h=1024, w=1024):
    try:
        load_sdxl()
        print(f"   Generating: {prompt[:50]}...")
        img = sdxl_pipe(
            prompt=prompt,
            negative_prompt="blurry, bad quality, distorted, ugly, text, watermark",
            height=h, width=w, num_inference_steps=30, guidance_scale=7.5
        ).images[0]
        img.save(output_path)
        print(f"   Image saved: {output_path}")
        return True
    except Exception as e:
        print(f"   Image gen error: {e}")
        return False

# ===== SVD =====

def load_svd():
    global svd_pipe
    if svd_pipe is None:
        unload_f5()
        unload_sdxl()
        gc.collect()
        torch.cuda.empty_cache()
        print("   Loading SVD...")
        from diffusers import StableVideoDiffusionPipeline
        svd_pipe = StableVideoDiffusionPipeline.from_pretrained(
            "stabilityai/stable-video-diffusion-img2vid",
            torch_dtype=torch.float16, variant="fp16"
        ).to("cuda")
        svd_pipe.enable_model_cpu_offload()
        print("   SVD loaded")

def unload_svd():
    global svd_pipe
    if svd_pipe is not None:
        del svd_pipe
        svd_pipe = None
        gc.collect()
        torch.cuda.empty_cache()

def gen_video(img_path, output_path):
    try:
        load_svd()
        img = Image.open(img_path).resize((1024, 576), Image.LANCZOS)
        print(f"   Generating video...")
        frames = svd_pipe(img, decode_chunk_size=4, num_frames=SVD_FRAMES, motion_bucket_id=SVD_MOTION).frames[0]
        from diffusers.utils import export_to_video
        export_to_video(frames, output_path, fps=SVD_FPS)
        print(f"   Video saved: {output_path}")
        return True
    except Exception as e:
        print(f"   Video gen error: {e}")
        return False

# ===== 輔助函數 =====

def create_text_frame(char, subtitle="", w=1920, h=1080):
    img = Image.new('RGB', (w, h), (30, 30, 50))
    draw = ImageDraw.Draw(img)
    try:
        font_big = ImageFont.truetype("/usr/share/fonts/truetype/noto/NotoSansCJK-Bold.ttc", 300)
        font_small = ImageFont.truetype("/usr/share/fonts/truetype/noto/NotoSansCJK-Regular.ttc", 48)
    except:
        font_big = ImageFont.load_default()
        font_small = ImageFont.load_default()
    bbox = draw.textbbox((0, 0), char, font=font_big)
    tw, th = bbox[2] - bbox[0], bbox[3] - bbox[1]
    draw.text(((w - tw) / 2, (h - th) / 2 - 80), char, fill=(255, 215, 0), font=font_big)
    if subtitle:
        bbox = draw.textbbox((0, 0), subtitle, font=font_small)
        tw = bbox[2] - bbox[0]
        draw.text(((w - tw) / 2, h - 150), subtitle, fill=(200, 200, 200), font=font_small)
    return img

def create_static_video(img_path, audio_path, output_path):
    from moviepy.editor import ImageClip, AudioFileClip
    audio = AudioFileClip(audio_path)
    clip = ImageClip(img_path).set_duration(audio.duration)
    clip = clip.set_audio(audio)
    clip.fps = 30
    clip.write_videofile(output_path, fps=30, codec="libx264", audio_codec="aac", logger=None)
    audio.close()
    clip.close()
    print(f"   Static video saved: {output_path}")

def merge_video_audio(video_path, audio_path, output_path):
    from moviepy.editor import VideoFileClip, AudioFileClip
    video = VideoFileClip(video_path)
    audio = AudioFileClip(audio_path)
    if video.duration < audio.duration:
        video = video.loop(duration=audio.duration)
    else:
        video = video.subclip(0, audio.duration)
    final = video.set_audio(audio)
    final.write_videofile(output_path, fps=30, codec="libx264", audio_codec="aac", logger=None)
    video.close()
    audio.close()
    final.close()

# ===== SSE 進度回報 =====

def sse_progress(progress, message_zh, message_en=""):
    """SSE 格式進度事件"""
    data = {
        "progress": progress,
        "message_zh": message_zh,
        "message_en": message_en or message_zh
    }
    return f"data: {json.dumps(data, ensure_ascii=False)}\n\n"

def sse_complete(video_b64, segments, scripts):
    """SSE 格式完成事件"""
    data = {
        "progress": 100,
        "message_zh": "✅ 完成！",
        "message_en": "✅ Complete!",
        "video_base64": video_b64,
        "segments": segments,
        "scripts": scripts
    }
    return f"data: {json.dumps(data, ensure_ascii=False)}\n\n"

def sse_error(error_msg):
    """SSE 格式錯誤事件"""
    data = {"error": error_msg}
    return f"data: {json.dumps(data, ensure_ascii=False)}\n\n"

# ===== API Endpoints =====

@app.route('/')
def home():
    return jsonify({"status": "running", "version": "v11-fixed2"})

@app.route('/health')
def health():
    return jsonify({"status": "healthy"})

@app.route('/recognize', methods=['POST'])
@app.route('/recognize/', methods=['POST'])
def recognize():
    print("\n[RECOGNIZE]")
    try:
        img = None
        if 'file' in request.files:
            file = request.files['file']
            if file:
                img_bytes = file.read()
                img = Image.open(io.BytesIO(img_bytes))
                print(f"   Got image: {file.filename}")
        if img is None:
            return jsonify({"error": "No image"}), 400
        if img.mode != 'RGB':
            img = img.convert('RGB')
        buffer = io.BytesIO()
        img.save(buffer, format='PNG')
        buffer.seek(0)
        img_base64 = base64.b64encode(buffer.read()).decode('utf-8')
        print(f"   Calling {VISION_MODEL}...")

        # 更強調 JSON 格式的 prompt
        prompt = """分析這張甲骨文圖片。

請嚴格按照以下JSON格式回答，不要使用markdown，不要加任何說明：
{"character": "對應的現代中文字", "pinyin": "拼音", "meaning": "含義說明", "confidence": 0.9}

只輸出JSON，不要其他內容。"""

        response = ollama.chat(
            model=VISION_MODEL,
            messages=[{'role': 'user', 'content': prompt, 'images': [img_base64]}]
        )
        result_text = response['message']['content']
        print(f"   Response: {result_text[:200]}...")

        # 先嘗試 JSON 解析
        result = extract_json(result_text)
        if result and result.get('character') and result.get('character') != '?':
            print(f"   Parsed JSON: {result}")
            return jsonify(result)

        # 如果 JSON 解析失敗，嘗試從 Markdown 格式提取
        print("   JSON parse failed, trying Markdown extraction...")
        result = parse_markdown_response(result_text)
        print(f"   Extracted from Markdown: {result}")

        # 如果還是沒提取到，返回原始回應
        if result.get('character') == '?' and len(result_text) > 10:
            result['meaning'] = result_text[:200]

        return jsonify(result)
    except Exception as e:
        print(f"   Error: {e}")
        traceback.print_exc()
        return jsonify({"error": str(e)}), 500

@app.route('/joke', methods=['POST'])
@app.route('/joke/', methods=['POST'])
def joke():
    print("\n[JOKE]")
    try:
        char = request.form.get('character', '字')
        meaning = request.form.get('meaning', '')
        lang = request.form.get('lang', 'zh-TW')
        voice = request.form.get('voice_style', 'trump')
        vid = get_voice_id(voice, lang)
        trait = get_trait(voice, lang)
        load_f5()
        if is_chinese(lang):
            p = f'用{trait}风格为「{char}」讲笑话，50-80字繁体中文，禁止前言，直接给台词：'
        else:
            p = f'Tell a joke about "{char}" in {trait} style, 50-80 words, NO preamble:'
        r = call_ollama(ollama.generate, model=OLLAMA_MODEL, prompt=p, stream=False)
        text = clean_script(r['response'].strip())
        audio_path = gen_audio(text, vid, lang, "/tmp/joke.wav")
        with open(audio_path, "rb") as f:
            audio_b64 = base64.b64encode(f.read()).decode()
        return jsonify({"joke_text": text, "audio_base64": audio_b64})
    except Exception as e:
        print(f"   Error: {e}")
        return jsonify({"error": str(e)}), 500

@app.route('/generate_video', methods=['POST'])
@app.route('/generate_video/', methods=['POST'])
def generate_video():
    print("\n[GENERATE_VIDEO]")
    try:
        char = request.form.get('character', '字')
        meaning = request.form.get('meaning', '')
        voice = request.form.get('voice', 'trump')
        lang = request.form.get('lang', 'zh-TW')
        style_prompt = request.form.get('style_prompt', '')  # 用戶選擇的風格

        vid = get_voice_id(voice, lang)
        trait = get_trait(voice, lang)
        char_img = get_char_image(voice)

        # 套用用戶選擇的風格
        if style_prompt:
            print(f"   Style: {style_prompt}")
            img_prompt = f"a beautiful {meaning} in the center, {char_img} standing next to it, {style_prompt}, detailed, 4k"
        else:
            img_prompt = f"a beautiful {meaning} in the center, {char_img} standing next to it and pointing, museum setting, professional lighting, detailed illustration, 4k"

        print(f"   Image prompt: {img_prompt[:100]}...")

        if is_chinese(lang):
            p = f'用{trait}风格为「{char}」（{meaning}）做解说，30-50字繁体中文，禁止前言：'
        else:
            p = f'Explain "{char}" ({meaning}) in {trait}, 30-50 words, NO preamble:'
        r = call_ollama(ollama.generate, model=OLLAMA_MODEL, prompt=p, stream=False)
        script = clean_script(r['response'].strip()) or f"這是{char}"
        load_f5()
        audio_path = gen_audio(script, vid, lang, "/tmp/video_audio.wav")
        if not gen_image(img_prompt, "/tmp/video_img.png", h=768, w=1024):
            create_text_frame(char, meaning, w=1024, h=768).save("/tmp/video_img.png")
        img = Image.open("/tmp/video_img.png").resize((1920, 1080), Image.LANCZOS)
        img.save("/tmp/video_img.png")
        create_static_video("/tmp/video_img.png", audio_path, "/tmp/video_out.mp4")
        with open("/tmp/video_out.mp4", "rb") as f:
            b64 = base64.b64encode(f.read()).decode()
        return jsonify({"video_base64": b64, "script": script})
    except Exception as e:
        print(f"   Error: {e}")
        return jsonify({"error": str(e)}), 500

# ==========================================
# 繪本說書人 (Streaming)
# ==========================================

@app.route('/storyteller', methods=['POST'])
@app.route('/storyteller/', methods=['POST'])
def storyteller():
    print("\n" + "="*60)
    print("[STORYTELLER - STORYBOOK MODE]")
    print("="*60)

    char = request.form.get('character', '字')
    meaning = request.form.get('meaning', char)
    va = request.form.get('voice_a', 'trump')
    vb = request.form.get('voice_b', 'obama')
    mode = request.form.get('mode', 'single')
    lang = request.form.get('lang', 'zh-TW')
    nsegs = int(request.form.get('segments', 4))
    nsegs = min(max(nsegs, 2), 6)

    def generate():
        try:
            na = va.replace('_zh', '').replace('_en', '')
            nb = vb.replace('_zh', '').replace('_en', '')
            vid_a = get_voice_id(na, lang)
            vid_b = get_voice_id(nb, lang)
            trait_a = get_trait(na, lang)
            trait_b = get_trait(nb, lang)
            cimg_a = get_char_image(na)
            cimg_b = get_char_image(nb)

            print(f"   Char: {char}, Segments: {nsegs}, Mode: {mode}")

            yield sse_progress(5, "正在生成腳本...", "Generating script...")

            ensure_ollama()

            # 生成腳本
            if is_chinese(lang):
                if mode == 'dialogue':
                    p = f'''你是甲骨文教育專家。請為甲骨文字「{char}」（意思：{meaning}）創作{nsegs}段教育對話。

對話必須包含：
1. 這個字的甲骨文字形像什麼（象形解釋）
2. 古人為什麼這樣設計這個字
3. 這個字在古代的用途或故事
4. 這個字演變到現代的過程

A（{na}）：{trait_a}
B（{nb}）：{trait_b}

嚴格交替A->B->A，每段30-50字繁體中文。
禁止前言、禁止動作描述、禁止括號。
JSON：{{"segments":[{{"speaker":"A","script":"台詞"}},{{"speaker":"B","script":"台詞"}}...]}}'''
                else:
                    p = f'''你是甲骨文教育專家。請用{trait_a}風格為甲骨文字「{char}」（意思：{meaning}）創作{nsegs}段教育故事。

故事必須包含：
1. 這個字的甲骨文字形像什麼（象形解釋）
2. 古人為什麼這樣設計這個字
3. 這個字在古代的用途或文化背景

每段30-50字繁體中文。禁止前言、禁止括號。
JSON：{{"segments":[{{"script":"台詞"}}...]}}'''
            else:
                if mode == 'dialogue':
                    p = f'''You are an ancient Chinese script expert. Create {nsegs} educational dialogue segments about the character "{char}" (meaning: {meaning}).

The dialogue MUST include:
1. What the oracle bone form looks like (pictographic explanation)
2. Why ancient Chinese designed it this way
3. Historical usage or stories about this character

A ({na}): {trait_a}
B ({nb}): {trait_b}

Alternate A->B->A, 30-50 words each, NO preamble.
JSON: {{"segments":[{{"speaker":"A","script":"text"}}...]}}'''
                else:
                    p = f'''You are an ancient Chinese script expert. Create {nsegs} educational story segments about "{char}" (meaning: {meaning}) in {trait_a} style.

The story MUST explain the pictographic origin and cultural significance.
30-50 words each. NO preamble.
JSON: {{"segments":[{{"script":"text"}}...]}}'''

            r = call_ollama(ollama.generate, model=OLLAMA_MODEL, prompt=p, stream=False, format="json")
            d = extract_json(r['response'])

            # Fallback - 使用與古文字相關的預設內容
            if not d or 'segments' not in d or len(d.get('segments', [])) < nsegs:
                print(f"   Fallback: Got {len(d.get('segments', [])) if d else 0} segments, need {nsegs}")
                if is_chinese(lang):
                    d = {"segments": [
                        {"speaker": "A", "script": f"你看這個「{char}」字！在甲骨文裡，它的形狀就像真正的{meaning}一樣，古人真是太聰明了！"},
                        {"speaker": "B", "script": f"沒錯，「{char}」是典型的象形字。三千年前的人觀察{meaning}的樣子，用簡單的線條把它刻在龜甲上。"},
                        {"speaker": "A", "script": f"這個字設計得非常好，簡直是藝術品！古人用「{char}」來記錄生活中的{meaning}，太有智慧了！"},
                        {"speaker": "B", "script": f"從甲骨文到現代漢字，「{char}」經歷了三千年的演變，但核心形象始終保留著，這就是漢字的魅力。"},
                        {"speaker": "A", "script": f"我要讓全世界都知道「{char}」這個字！這是中華文化最棒的部分！"},
                        {"speaker": "B", "script": f"讓我們一起傳承這份珍貴的文化遺產，讓更多人認識甲骨文的智慧。"},
                    ][:nsegs]}
                else:
                    d = {"segments": [
                        {"speaker": "A", "script": f"Look at this '{char}'! In ancient Chinese script, it looks just like a real {meaning}. Ancient Chinese were brilliant!"},
                        {"speaker": "B", "script": f"Indeed, '{char}' is a pictographic character. 3000 years ago, people observed {meaning} and drew its image with simple strokes."},
                        {"speaker": "A", "script": f"This character design is fantastic! The ancients recorded {meaning} in their daily life with such wisdom!"},
                        {"speaker": "B", "script": f"From ancient script to modern Chinese, '{char}' evolved over 3000 years while preserving its core image."},
                    ][:nsegs]}

            segs = d['segments'][:nsegs]
            for i, s in enumerate(segs):
                s['script'] = clean_script(s.get('script', f'Segment {i+1}'))
                if mode == 'dialogue':
                    s['speaker'] = 'A' if i % 2 == 0 else 'B'
                else:
                    s['speaker'] = 'narrator'

            yield sse_progress(10, f"腳本完成 ({len(segs)} 段)", f"Script ready ({len(segs)} segments)")

            # 生成每一頁
            clips = []
            total = len(segs)

            for i, seg in enumerate(segs):
                page = i + 1
                base = 10 + (i * 80 // total)
                script = seg['script']
                speaker = seg.get('speaker', 'A')

                if mode == 'dialogue':
                    vid = vid_a if speaker == 'A' else vid_b
                    cimg = cimg_a if speaker == 'A' else cimg_b
                else:
                    vid = vid_a
                    cimg = cimg_a

                yield sse_progress(base + 5, f"第{page}/{total}頁：語音...", f"Page {page}/{total}: Audio...")
                load_f5()
                audio_path = f"/tmp/sb_seg{i}_audio.wav"
                gen_audio(script, vid, lang, audio_path)

                yield sse_progress(base + 15, f"第{page}/{total}頁：插圖...", f"Page {page}/{total}: Image...")
                scene = STORYBOOK_SCENES[i % len(STORYBOOK_SCENES)]

                # 圖片 prompt：明確要求動物/事物 + 角色
                # 例如「羊」→ "a cute sheep" + "Trump pointing at it"
                img_prompt = f"a beautiful {meaning} in the center, {cimg} standing next to it and pointing, {scene}, detailed illustration, children's book style, vibrant colors, 4k"
                print(f"   Image prompt: {img_prompt[:100]}...")

                img_path = f"/tmp/sb_seg{i}_img.png"
                if not gen_image(img_prompt, img_path, h=1080, w=1920):
                    create_text_frame(char, script[:30]).save(img_path)

                yield sse_progress(base + 20, f"第{page}/{total}頁：合成...", f"Page {page}/{total}: Composing...")
                seg_video = f"/tmp/sb_seg{i}_video.mp4"
                create_static_video(img_path, audio_path, seg_video)
                clips.append(seg_video)

            yield sse_progress(92, "合併繪本...", "Assembling...")

            from moviepy.editor import VideoFileClip, concatenate_videoclips
            video_clips = [VideoFileClip(c) for c in clips]
            final = concatenate_videoclips(video_clips, method="compose")
            final.write_videofile("/tmp/sb_final.mp4", fps=30, codec="libx264", audio_codec="aac", logger=None)
            for c in video_clips:
                c.close()

            with open("/tmp/sb_final.mp4", "rb") as f:
                b64 = base64.b64encode(f.read()).decode()

            scripts_out = [{"speaker": s.get('speaker', 'narrator'), "script": s['script']} for s in segs]

            yield sse_complete(b64, len(segs), scripts_out)
            print("   STORYBOOK COMPLETE!")

        except Exception as e:
            print(f"   ERROR: {e}")
            traceback.print_exc()
            yield sse_error(str(e))

    return Response(
        stream_with_context(generate()),
        mimetype='text/event-stream',
        headers={'Cache-Control': 'no-cache', 'X-Accel-Buffering': 'no'}
    )

# ==========================================
# 動態說書人 (SVD)
# ==========================================

@app.route('/storyteller_animated', methods=['POST'])
@app.route('/storyteller_animated/', methods=['POST'])
def storyteller_animated():
    print("\n" + "="*60)
    print("[STORYTELLER-ANIMATED with SVD]")
    print("="*60)

    char = request.form.get('character', '字')
    meaning = request.form.get('meaning', char)
    va = request.form.get('voice_a', 'trump')
    vb = request.form.get('voice_b', 'obama')
    mode = request.form.get('mode', 'single')
    lang = request.form.get('lang', 'zh-TW')
    nsegs = int(request.form.get('segments', 3))
    nsegs = min(max(nsegs, 2), 4)

    def generate():
        try:
            na = va.replace('_zh', '').replace('_en', '')
            nb = vb.replace('_zh', '').replace('_en', '')
            vid_a = get_voice_id(na, lang)
            vid_b = get_voice_id(nb, lang)
            trait_a = get_trait(na, lang)
            trait_b = get_trait(nb, lang)
            cimg_a = get_char_image(na)
            cimg_b = get_char_image(nb)

            print(f"   Char: {char}, Segments: {nsegs}, Mode: {mode}")

            yield sse_progress(3, "正在生成腳本...", "Generating script...")

            ensure_ollama()

            # 生成腳本
            if is_chinese(lang):
                if mode == 'dialogue':
                    p = f'''你是甲骨文教育專家。請為甲骨文字「{char}」（意思：{meaning}）創作{nsegs}段教育對話。

對話必須包含：
1. 這個字的甲骨文字形像什麼（象形解釋）
2. 古人為什麼這樣設計這個字
3. 這個字在古代的用途或故事
4. 這個字演變到現代的過程

A（{na}）：{trait_a}
B（{nb}）：{trait_b}

嚴格交替A->B->A，每段30-50字繁體中文。
禁止前言、禁止動作描述、禁止括號。
JSON：{{"segments":[{{"speaker":"A","script":"台詞"}},{{"speaker":"B","script":"台詞"}}...]}}'''
                else:
                    p = f'''你是甲骨文教育專家。請用{trait_a}風格為甲骨文字「{char}」（意思：{meaning}）創作{nsegs}段教育故事。

故事必須包含：
1. 這個字的甲骨文字形像什麼（象形解釋）
2. 古人為什麼這樣設計這個字
3. 這個字在古代的用途或文化背景

每段30-50字繁體中文。禁止前言、禁止括號。
JSON：{{"segments":[{{"script":"台詞"}}...]}}'''
            else:
                if mode == 'dialogue':
                    p = f'''You are an ancient Chinese script expert. Create {nsegs} educational dialogue segments about the character "{char}" (meaning: {meaning}).

The dialogue MUST include:
1. What the oracle bone form looks like (pictographic explanation)
2. Why ancient Chinese designed it this way
3. Historical usage or stories about this character

A ({na}): {trait_a}
B ({nb}): {trait_b}

Alternate A->B->A, 30-50 words each, NO preamble.
JSON: {{"segments":[{{"speaker":"A","script":"text"}}...]}}'''
                else:
                    p = f'''You are an ancient Chinese script expert. Create {nsegs} educational story segments about "{char}" (meaning: {meaning}) in {trait_a} style.

The story MUST explain the pictographic origin and cultural significance.
30-50 words each. NO preamble.
JSON: {{"segments":[{{"script":"text"}}...]}}'''

            r = call_ollama(ollama.generate, model=OLLAMA_MODEL, prompt=p, stream=False, format="json")
            d = extract_json(r['response'])

            # Fallback - 使用與古文字相關的預設內容
            if not d or 'segments' not in d or len(d.get('segments', [])) < nsegs:
                print(f"   Fallback: Got {len(d.get('segments', [])) if d else 0} segments, need {nsegs}")
                if is_chinese(lang):
                    d = {"segments": [
                        {"speaker": "A", "script": f"你看這個「{char}」字！在甲骨文裡，它的形狀就像真正的{meaning}一樣，古人真是太聰明了！"},
                        {"speaker": "B", "script": f"沒錯，「{char}」是典型的象形字。三千年前的人觀察{meaning}的樣子，用簡單的線條把它刻在龜甲上。"},
                        {"speaker": "A", "script": f"這個字設計得非常好，簡直是藝術品！古人用「{char}」來記錄生活中的{meaning}，太有智慧了！"},
                        {"speaker": "B", "script": f"從甲骨文到現代漢字，「{char}」經歷了三千年的演變，但核心形象始終保留著，這就是漢字的魅力。"},
                    ][:nsegs]}
                else:
                    d = {"segments": [
                        {"speaker": "A", "script": f"Look at this '{char}'! In ancient Chinese script, it looks just like a real {meaning}. Ancient Chinese were brilliant!"},
                        {"speaker": "B", "script": f"Indeed, '{char}' is a pictographic character. 3000 years ago, people observed {meaning} and drew its image with simple strokes."},
                        {"speaker": "A", "script": f"This character design is fantastic! The ancients recorded {meaning} in their daily life with such wisdom!"},
                        {"speaker": "B", "script": f"From ancient script to modern Chinese, '{char}' evolved over 3000 years while preserving its core image."},
                    ][:nsegs]}

            segs = d['segments'][:nsegs]
            for i, s in enumerate(segs):
                s['script'] = clean_script(s.get('script', f'Segment {i+1}'))
                if mode == 'dialogue':
                    s['speaker'] = 'A' if i % 2 == 0 else 'B'
                else:
                    s['speaker'] = 'narrator'

            yield sse_progress(8, f"腳本完成 ({len(segs)} 段動畫)", f"Script ready ({len(segs)} animations)")

            # 生成每段動畫
            clips = []
            total = len(segs)

            for i, seg in enumerate(segs):
                num = i + 1
                base = 8 + (i * 85 // total)
                script = seg['script']
                speaker = seg.get('speaker', 'A')

                if mode == 'dialogue':
                    vid = vid_a if speaker == 'A' else vid_b
                    cimg = cimg_a if speaker == 'A' else cimg_b
                else:
                    vid = vid_a
                    cimg = cimg_a

                yield sse_progress(base + 3, f"動畫{num}/{total}：語音...", f"Anim {num}/{total}: Audio...")
                load_f5()
                audio_path = f"/tmp/seg{i}_audio.wav"
                gen_audio(script, vid, lang, audio_path)

                yield sse_progress(base + 8, f"動畫{num}/{total}：圖片...", f"Anim {num}/{total}: Image...")

                # 圖片 prompt：明確要求動物/事物 + 角色
                img_prompt = f"a beautiful {meaning} in the center, {cimg} standing next to it and explaining, educational illustration, children's book style, vibrant colors, 4k"
                print(f"   Image prompt: {img_prompt[:100]}...")

                img_path = f"/tmp/seg{i}_img.png"
                if not gen_image(img_prompt, img_path):
                    create_text_frame(char, script[:20]).save(img_path)

                yield sse_progress(base + 15, f"動畫{num}/{total}：SVD ⏳", f"Anim {num}/{total}: SVD ⏳")
                vid_path = f"/tmp/seg{i}_vid.mp4"
                if not gen_video(img_path, vid_path):
                    from moviepy.editor import ImageClip
                    ic = ImageClip(img_path).set_duration(4)
                    ic.fps = 30
                    ic.write_videofile(vid_path, fps=30, codec="libx264", logger=None)

                yield sse_progress(base + 22, f"動畫{num}/{total}：合併...", f"Anim {num}/{total}: Merge...")
                final_path = f"/tmp/seg{i}_final.mp4"
                merge_video_audio(vid_path, audio_path, final_path)
                clips.append(final_path)

            yield sse_progress(95, "合併所有動畫...", "Concatenating...")

            from moviepy.editor import VideoFileClip, concatenate_videoclips
            video_clips = [VideoFileClip(c) for c in clips]
            final = concatenate_videoclips(video_clips, method="compose")
            final.write_videofile("/tmp/final.mp4", fps=30, codec="libx264", audio_codec="aac", logger=None)
            for c in video_clips:
                c.close()

            with open("/tmp/final.mp4", "rb") as f:
                b64 = base64.b64encode(f.read()).decode()

            scripts_out = [{"speaker": s.get('speaker', 'narrator'), "script": s['script']} for s in segs]

            yield sse_complete(b64, len(segs), scripts_out)
            print("   ANIMATED COMPLETE!")

        except Exception as e:
            print(f"   ERROR: {e}")
            traceback.print_exc()
            yield sse_error(str(e))

    return Response(
        stream_with_context(generate()),
        mimetype='text/event-stream',
        headers={'Cache-Control': 'no-cache', 'X-Accel-Buffering': 'no'}
    )

# ===== 啟動 =====

if __name__ == '__main__':
    print("\n" + "="*60)
    print("   ORACLE BONE DICTIONARY v11-fixed2")
    print("="*60)

    ensure_ollama()

    print("\n[Voices]")
    for n, r in VOICE_REFERENCES.items():
        ok = "OK" if os.path.exists(r['path']) else "X"
        print(f"   {n}: {ok}")

    from pyngrok import ngrok
    try:
        from google.colab import userdata
        ngrok_token = userdata.get('NGROK_AUTHTOKEN')
        if ngrok_token:
            ngrok.set_auth_token(ngrok_token)
            print("\n[ngrok] Token loaded")
    except:
        pass

    url = ngrok.connect(5000)
    print(f"\n{'='*60}")
    print(f"   URL: {url}")
    print(f"{'='*60}\n")

    app.run(host='0.0.0.0', port=5000, debug=False)